// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0--rc2
// source: cipher.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cipher_Proccess_FullMethodName = "/Cipher/proccess"
)

// CipherClient is the client API for Cipher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CipherClient interface {
	Proccess(ctx context.Context, in *CipherRequest, opts ...grpc.CallOption) (*CipherResponse, error)
}

type cipherClient struct {
	cc grpc.ClientConnInterface
}

func NewCipherClient(cc grpc.ClientConnInterface) CipherClient {
	return &cipherClient{cc}
}

func (c *cipherClient) Proccess(ctx context.Context, in *CipherRequest, opts ...grpc.CallOption) (*CipherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CipherResponse)
	err := c.cc.Invoke(ctx, Cipher_Proccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CipherServer is the server API for Cipher service.
// All implementations must embed UnimplementedCipherServer
// for forward compatibility.
type CipherServer interface {
	Proccess(context.Context, *CipherRequest) (*CipherResponse, error)
	mustEmbedUnimplementedCipherServer()
}

// UnimplementedCipherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCipherServer struct{}

func (UnimplementedCipherServer) Proccess(context.Context, *CipherRequest) (*CipherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proccess not implemented")
}
func (UnimplementedCipherServer) mustEmbedUnimplementedCipherServer() {}
func (UnimplementedCipherServer) testEmbeddedByValue()                {}

// UnsafeCipherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CipherServer will
// result in compilation errors.
type UnsafeCipherServer interface {
	mustEmbedUnimplementedCipherServer()
}

func RegisterCipherServer(s grpc.ServiceRegistrar, srv CipherServer) {
	// If the following call pancis, it indicates UnimplementedCipherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cipher_ServiceDesc, srv)
}

func _Cipher_Proccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CipherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServer).Proccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cipher_Proccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServer).Proccess(ctx, req.(*CipherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cipher_ServiceDesc is the grpc.ServiceDesc for Cipher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cipher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cipher",
	HandlerType: (*CipherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "proccess",
			Handler:    _Cipher_Proccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cipher.proto",
}
