// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: cipher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CipherRequestCipherType int32

const (
	CipherRequest_UNKNOWN  CipherRequestCipherType = 0
	CipherRequest_CEASAR   CipherRequestCipherType = 1
	CipherRequest_VIGENERE CipherRequestCipherType = 2
	CipherRequest_OTP      CipherRequestCipherType = 3
)

// Enum value maps for CipherRequestCipherType.
var (
	CipherRequestCipherType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CEASAR",
		2: "VIGENERE",
		3: "OTP",
	}
	CipherRequestCipherType_value = map[string]int32{
		"UNKNOWN":  0,
		"CEASAR":   1,
		"VIGENERE": 2,
		"OTP":      3,
	}
)

func (x CipherRequestCipherType) Enum() *CipherRequestCipherType {
	p := new(CipherRequestCipherType)
	*p = x
	return p
}

func (x CipherRequestCipherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipherRequestCipherType) Descriptor() protoreflect.EnumDescriptor {
	return file_cipher_proto_enumTypes[0].Descriptor()
}

func (CipherRequestCipherType) Type() protoreflect.EnumType {
	return &file_cipher_proto_enumTypes[0]
}

func (x CipherRequestCipherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipherRequestCipherType.Descriptor instead.
func (CipherRequestCipherType) EnumDescriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{0, 0}
}

type CipherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cipher bool                    `protobuf:"varint,1,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Key    *string                 `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Text   string                  `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Type   CipherRequestCipherType `protobuf:"varint,4,opt,name=type,proto3,enum=CipherRequestCipherType" json:"type,omitempty"`
}

func (x *CipherRequest) Reset() {
	*x = CipherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cipher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CipherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherRequest) ProtoMessage() {}

func (x *CipherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cipher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherRequest.ProtoReflect.Descriptor instead.
func (*CipherRequest) Descriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{0}
}

func (x *CipherRequest) GetCipher() bool {
	if x != nil {
		return x.Cipher
	}
	return false
}

func (x *CipherRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *CipherRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CipherRequest) GetType() CipherRequestCipherType {
	if x != nil {
		return x.Type
	}
	return CipherRequest_UNKNOWN
}

type CipherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CipherResponse) Reset() {
	*x = CipherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cipher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CipherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherResponse) ProtoMessage() {}

func (x *CipherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cipher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherResponse.ProtoReflect.Descriptor instead.
func (*CipherResponse) Descriptor() ([]byte, []int) {
	return file_cipher_proto_rawDescGZIP(), []int{1}
}

func (x *CipherResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_cipher_proto protoreflect.FileDescriptor

var file_cipher_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7,
	0x01, 0x0a, 0x0d, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x3c, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x45, 0x41, 0x53, 0x41, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x49, 0x47,
	0x45, 0x4e, 0x45, 0x52, 0x45, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x54, 0x50, 0x10, 0x03,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x35,
	0x0a, 0x06, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6d, 0x61, 0x70, 0x6f, 0x73, 0x68, 0x74, 0x69, 0x62, 0x61,
	0x6e, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cipher_proto_rawDescOnce sync.Once
	file_cipher_proto_rawDescData = file_cipher_proto_rawDesc
)

func file_cipher_proto_rawDescGZIP() []byte {
	file_cipher_proto_rawDescOnce.Do(func() {
		file_cipher_proto_rawDescData = protoimpl.X.CompressGZIP(file_cipher_proto_rawDescData)
	})
	return file_cipher_proto_rawDescData
}

var file_cipher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cipher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cipher_proto_goTypes = []any{
	(CipherRequestCipherType)(0), // 0: CipherRequest.cipherType
	(*CipherRequest)(nil),        // 1: CipherRequest
	(*CipherResponse)(nil),       // 2: CipherResponse
}
var file_cipher_proto_depIdxs = []int32{
	0, // 0: CipherRequest.type:type_name -> CipherRequest.cipherType
	1, // 1: Cipher.proccess:input_type -> CipherRequest
	2, // 2: Cipher.proccess:output_type -> CipherResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cipher_proto_init() }
func file_cipher_proto_init() {
	if File_cipher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cipher_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CipherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cipher_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CipherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cipher_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cipher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cipher_proto_goTypes,
		DependencyIndexes: file_cipher_proto_depIdxs,
		EnumInfos:         file_cipher_proto_enumTypes,
		MessageInfos:      file_cipher_proto_msgTypes,
	}.Build()
	File_cipher_proto = out.File
	file_cipher_proto_rawDesc = nil
	file_cipher_proto_goTypes = nil
	file_cipher_proto_depIdxs = nil
}
